### ISSUE TITLE
Problema com biblioteca

### ISSUE THREAD

**Issue by spec-r** [niobio-cash/niobio-node-daemon#31]
Atualizei meu Ubuntu para a versão 18.4 e por problemas de versões diferentes de biblioteca, não consigo mais abrir o CLI.
Já tentei forçar a instalação, mas por incompatibilidade não funcionou.
Tem alguma alternativa?

```
starsplash@E5430:~/niobio-cash.linux64.CLI.1-6-2$ ./niobiod 
./niobiod: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```

**Comment by helder-garcia** [comment]
Tenta instalar a boost 1.58
sudo apt-get -y install libboost1.58-all-dev

**Comment by spec-r** [comment]
Já tinha feito isso, também tentei instalar manualmente o pacote deb, mas não funcionou.

starsplash@E5430:~/niobio-cash.linux64.CLI.1-6-2$ sudo apt-get -y install libboost1.58-all-dev
[sudo] senha para starsplash: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote libboost1.58-all-dev
E: Couldn't find any package by glob 'libboost1.58-all-dev'
E: Não foi possível encontrar o pacote através da expressão regular 'libboost1.58-all-dev'

**Comment by helder-garcia** [comment]
Instala todas as ferramentas e compila
sudo apt-get -y install build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost-all-dev
git clone https://github.com/niobio-cash/niobio-node-daemon.git
cd niobio-node-daemon
mkdir build
cmake ..
make

Os binários vão estar embaixo de build/src

**Comment by spec-r** [comment]
Minha versão do GCC é diferente e também não é possivel o downgrade.

`starsplash@E5430:~/niobio-node-daemon/build$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified


-- Configuring done
-- Generating done
-- Build files have been written to: /home/starsplash/niobio-node-daemon/build
`
E por isso também não compila.

`
starsplash@E5430:~/niobio-node-daemon/build$ make
Scanning dependencies of target version
fatal: No annotated tags can describe '69c957371a0973f1e258476dfed6690ace24773b'.
However, there were unannotated tags: try --tags.
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.


[  0%] Built target version
Scanning dependencies of target upnpc-static
[  0%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/igd_desc_parse.c.o
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/miniupnpc.c.o
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/minixml.c.o
[  2%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/minisoap.c.o
[  2%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/miniwget.c.o
[  3%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpc.c.o
/home/starsplash/niobio-node-daemon/external/miniupnpc/upnpc.c: In function ‘main’:
/home/starsplash/niobio-node-daemon/external/miniupnpc/upnpc.c:130:23: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
   snprintf(index, 6, "%d", i);
                       ^~
/home/starsplash/niobio-node-daemon/external/miniupnpc/upnpc.c:130:22: note: directive argument in the range [0, 2147483647]
   snprintf(index, 6, "%d", i);
                      ^~~~
In file included from /usr/include/stdio.h:862:0,
                 from /home/starsplash/niobio-node-daemon/external/miniupnpc/upnpc.c:8:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 11 bytes into a destination of size 6
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
external/miniupnpc/CMakeFiles/upnpc-static.dir/build.make:182: recipe for target 'external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpc.c.o' failed
make[2]: *** [external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpc.c.o] Error 1
CMakeFiles/Makefile2:143: recipe for target 'external/miniupnpc/CMakeFiles/upnpc-static.dir/all' failed
make[1]: *** [external/miniupnpc/CMakeFiles/upnpc-static.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by helder-garcia** [comment]
Faz o checkout da branch devel2:
cd niobio-node-daemon
git pull
git checkout devel2
git pull
cd build
cmake ..
make

**Comment by spec-r** [comment]
Agora foi!
Obrigado

```
Scanning dependencies of target ConnectivityTool
[ 99%] Building CXX object src/CMakeFiles/ConnectivityTool.dir/ConnectivityTool/ConnectivityTool.cpp.o
[100%] Linking CXX executable connectivity_tool
[100%] Built target ConnectivityTool

starsplash@E5430:~/niobio-node-daemon/build$ cd src/

starsplash@E5430:~/niobio-node-daemon/build/src$ ./niobiod 
2018-Jul-24 18:07:28.970860 INFO    niobio v1.6.2-Sekhmet ()
2018-Jul-24 18:07:28.971136 INFO    Module folder: ./niobiod
2018-Jul-24 18:07:28.982161 INFO    Initializing p2p server...
2018-Jul-24 18:07:28.982382 INFO    Generated new peer ID: 14470287758598991340
2018-Jul-24 18:07:28.982436 INFO    Network: 958b4459-c496-6b98-24ba-906d89efce2a
2018-Jul-24 18:07:28.982480 INFO    Binding on 0.0.0.0:8313
2018-Jul-24 18:07:28.982544 INFO    Net service binded on 0.0.0.0:8313
2018-Jul-24 18:07:28.982588 INFO    Attempting to add IGD port mapping.
2018-Jul-24 18:07:30.051965 INFO    Added IGD port mapping.
2018-Jul-24 18:07:30.052192 INFO    P2p server initialized OK
2018-Jul-24 18:07:30.052336 INFO    Initializing core...
2018-Jul-24 18:07:30.053265 INFO    Blockchain not loaded, generating genesis block.
2018-Jul-24 18:07:30.053695 INFO    +++++ Blockchain loaded to height: 0
2018-Jul-24 18:07:30.053893 INFO    Blockchain initialized. last block: 0, d2211.h16.m07.s30 time ago, current difficulty: 1
2018-Jul-24 18:07:30.054049 INFO    Core initialized OK
2018-Jul-24 18:07:30.054481 INFO    Starting core rpc server on address 127.0.0.1:8314
2018-Jul-24 18:07:30.054739 INFO    RPC server binded to loopback, you're not opened to the world. Very well.
2018-Jul-24 18:07:30.054880 INFO    Core rpc server started ok
2018-Jul-24 18:07:30.055001 INFO    Starting p2p net loop...
2018-Jul-24 18:07:30.055117 INFO    Starting node_server
```

**Comment by helder-garcia** [comment]
Você pode fazer o pull/cmake/make novamente e me informar se continua compilando?

**Comment by spec-r** [comment]
Deletei a pasta niobio-node-daemon inteira e clonei a git novamente.
Compilou sem nenhum problema.
