### ISSUE TITLE
daemon stuck on  block: 153559

### ISSUE THREAD

**Issue by prox443** [niobio-cash/niobio-node-daemon#38]
i have an issue with your last update
"ERROR   CHECKPOINT VALIDATION FAILED"
and me daemon stuck on  block: 153559

Ex Log:
`2018-Nov-25 12:04:27.200101 ERROR   CHECKPOINT VALIDATION FAILED
2018-Nov-25 12:04:29.895697 ERROR   [179.157.84.11:60764 INC] sent wrong block: failed to parse and validate block:
0600f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f70100cce0dddf05f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f78a3821d701010000002303210033bbf40739e1d15af824f68ac905084ca83cfbaa483eb8d4cd8584982be2459801e2af0901ffd8af090af9fbdff90302403f52f797317affa624308ebc668474db3ee243e629a2036396e9cead942678f9fbdff903021fa9dd8954415161d4cb1077f68423836afc9df1f646c84b41da44a1311b38d58c0702da8e3efa57633556ac1a67b40bd35818ae6104d0726989a05a8007f7cf732b03b8170289a017891bb626df10660f2965979561bc7320f1fbe176367c0f1df512b7928d904e0208bd7dec9aab2651fddad6e21d5224459ec771a92132942f416e69618429590380b518023de9347a913b3ed50fc763394b2135573f5123478a31f300182bec74361dd9ccc0843d02852e41fdfefa71fa68329d93bf4908f41e43b9de42769fe2edcd673bf17c1f2f8095f52a02ec55dace4f10f78b2d20ddb48e006c1725bf21b447dcc1e399d122ec0593f31a80b4c4c321029f3eed50d86e5322d7750234b887b7cf06f9ab2e70fdeeba533be36cac9d75f480c8afa025028cb16a11e5fb5183ea752831e2a3b309cce66b1109ae20c5917e539438827e8d3401ec9a8aac795b1915c1433336491984aee906ad310d2a46f021279b58e0ab9ef402110000000002af2eac00000000000000000009b5e9a2170ec79f137af84344aa5146786c042198f6d773eb89d1390e3c867c6dfd09f55cb3794876bfe9741e22f84931987a61db87a053c56b54bd49742385e5b337801cd374521468f68c942c8af5e4ba070584a0699e4343855dbfcee154d2e71308d760c5b1e5c2250c3178ad27cf2b5f18fca9e53aac056d113a419648f41942e0989886abb01e93bb03db9af70b434ed62c489876e90b2d1108b4c6a8f03e535201c3650e2e1dfca05632efb66987cc735f643420205614c599a6f6385f79354039cab6546f5e12a846a83d747596dec9490b6da954c41639079540fdbd911829fcb753741b6c138f5ce8cd11a4d9dbc2eccb895192c63d3458165e63ba5acfd9ac97fecf7451d82d7b9b5278712ccdf978c7c682c4ebc606552726b882
 dropping connection
2018-Nov-25 12:04:32.081030 INFO    [216.244.77.114:42777 INC] Sync data returned unknown top block: 153559 -> 153729 [170 blocks (0 days) behind]
2018-Nov-25 12:04:32.081030 INFO    SYNCHRONIZATION started
2018-Nov-25 12:04:34.584598 ERROR   CHECKPOINT FAILED FOR HEIGHT 153560. EXPECTED HASH: d4199fa557bbb0e2d29dc306a65c731f210fe4cf47293230828ccba96b13929d, FETCHED HASH: 409808c832183bc54cc712528e9b13b47771138f59c41e5e105a3f7bc1dcfd86
2018-Nov-25 12:04:34.584999 ERROR   CHECKPOINT VALIDATION FAILED
`

**Comment by helder-garcia** [comment]
Please, send first 100 lines of daemon log.

**Comment by prox443** [comment]
Logs:
`2018-Nov-25 12:34:15.216649 INFO    [daemon] niobio v1.6.6-Ptah ()
2018-Nov-25 12:34:15.217014 INFO    [daemon] Module folder: ./niobiod
2018-Nov-25 12:34:15.515840 INFO    [checkpoints] Checkpoint already exists for height: 14000. Ignoring DNS checkpoint.
2018-Nov-25 12:34:15.516301 INFO    [daemon] Initializing p2p server...
2018-Nov-25 12:34:15.516596 INFO    [node_server] Generated new peer ID: 12763588807126227970
2018-Nov-25 12:34:15.516794 INFO    [node_server] Network: 958b4459-c496-6b98-24ba-906d89efce2a
2018-Nov-25 12:34:15.516979 INFO    [node_server] Binding on 0.0.0.0:8313
2018-Nov-25 12:34:15.517167 INFO    [node_server] Net service binded on 0.0.0.0:8313
2018-Nov-25 12:34:15.517350 INFO    [node_server] Attempting to add IGD port mapping.
2018-Nov-25 12:34:19.522076 INFO    [node_server] No IGD was found.
2018-Nov-25 12:34:19.522458 INFO    [daemon] P2p server initialized OK
2018-Nov-25 12:34:19.522649 INFO    [daemon] Initializing core...
2018-Nov-25 12:34:19.523014 INFO    [Blockchain] Blockchain not loaded, generating genesis block.
2018-Nov-25 12:34:19.523351 INFO    [Blockchain] +++++ Blockchain loaded to height: 0
2018-Nov-25 12:34:19.523565 INFO    [Blockchain] Blockchain initialized. last block: 0, d2335.h06.m34.s19 time ago, current difficulty: 1
2018-Nov-25 12:34:19.523742 INFO    [daemon] Core initialized OK
2018-Nov-25 12:34:19.524036 INFO    [daemon] Starting core rpc server on address 127.0.0.1:8314
2018-Nov-25 12:34:19.524299 INFO    [RpcServer] RPC server binded to loopback, you're not opened to the world. Very well.
2018-Nov-25 12:34:19.524483 INFO    [daemon] Core rpc server started ok
2018-Nov-25 12:34:19.524652 INFO    [daemon] Starting p2p net loop...
2018-Nov-25 12:34:19.524796 INFO    [node_server] Starting node_server
2018-Nov-25 12:34:20.425200 INFO    [protocol] [187.54.130.234:29222 INC] Sync data returned unknown top block: 0 -> 153729 [153729 blocks (427 days) behind]
2018-Nov-25 12:34:20.425200 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:20.646899 INFO    [protocol] [216.244.77.114:56783 INC] Sync data returned unknown top block: 0 -> 153729 [153729 blocks (427 days) behind]
2018-Nov-25 12:34:20.646899 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:22.996575 INFO    [checkpoints] CHECKPOINT PASSED FOR HEIGHT 1 62b3674f55adf428b586c9c45ec0f0c57660c61ac28c3f3bc087f8fccf246230
2018-Nov-25 12:34:23.622140 INFO    [Blockchain] +++++ Blockchain loaded to height: 100
2018-Nov-25 12:34:25.190122 INFO    [protocol] [83.132.242.238:8313 OUT] Sync data returned unknown top block: 192 -> 153560 [153368 blocks (426 days) behind]
2018-Nov-25 12:34:25.190122 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:25.385199 INFO    [protocol] [83.135.217.128:63739 INC] Sync data returned unknown top block: 192 -> 153729 [153537 blocks (426 days) behind]
2018-Nov-25 12:34:25.385199 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:25.412756 INFO    [Blockchain] +++++ Blockchain loaded to height: 200
2018-Nov-25 12:34:25.669516 INFO    [Blockchain] +++++ Blockchain loaded to height: 300
2018-Nov-25 12:34:26.030110 INFO    [Blockchain] +++++ Blockchain loaded to height: 400
2018-Nov-25 12:34:26.422760 INFO    [Blockchain] +++++ Blockchain loaded to height: 500
2018-Nov-25 12:34:26.680781 INFO    [Blockchain] +++++ Blockchain loaded to height: 600
2018-Nov-25 12:34:27.044846 INFO    [Blockchain] +++++ Blockchain loaded to height: 700
2018-Nov-25 12:34:27.305388 INFO    [Blockchain] +++++ Blockchain loaded to height: 800
2018-Nov-25 12:34:27.324796 INFO    [protocol] [177.102.72.226:8313 OUT] Sync data returned unknown top block: 805 -> 64863 [64058 blocks (177 days) behind]
2018-Nov-25 12:34:27.324796 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:27.681664 INFO    [Blockchain] +++++ Blockchain loaded to height: 900
2018-Nov-25 12:34:27.793103 INFO    [protocol] [24.131.39.65:8313 OUT] Sync data returned unknown top block: 931 -> 154415 [153484 blocks (426 days) behind]
2018-Nov-25 12:34:27.793103 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-25 12:34:28.073281 INFO    [Blockchain] +++++ Blockchain loaded to height: 1000
2018-Nov-25 12:34:28.342993 INFO    [Blockchain] +++++ Blockchain loaded to height: 1100
2018-Nov-25 12:34:28.629537 INFO    [protocol] [177.86.124.7:53084 INC] Sync data returned unknown top block: 1183 -> 153729 [152546 blocks (423 days) behind]
2018-Nov-25 12:34:28.629537 INFO    [protocol] SYNCHRONIZATION started
`

and last log
`2018-Nov-26 04:16:57.260607 ERROR   [checkpoints] CHECKPOINT FAILED FOR HEIGHT 153560. EXPECTED HASH: d4199fa557bbb0e2d29dc306a65c731f210fe4cf47293230828ccba96b13929d, FETCHED HASH: 409808c832183bc54cc712528e9b13b47771138f59c41e5e105a3f7bc1dcfd86
2018-Nov-26 04:16:57.261200 ERROR   [Blockchain] CHECKPOINT VALIDATION FAILED
2018-Nov-26 04:16:57.448607 ERROR   [protocol] [191.54.114.61:65286 INC] sent wrong block: failed to parse and validate block: ^M
0600f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f70100cce0dddf05f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f78a3821d701010000002303210033bbf40739e1d15af824f68ac905084ca83cfbaa483eb8d4cd8584982be2459801e2af0901ffd8af090af9fbdff90302403f52f797317affa624308ebc668474db3ee243e629a2036396e9cead942678f9fbdff903021fa9dd8954415161d4cb1077f68423836afc9df1f646c84b41da44a1311b38d58c0702da8e3efa57633556ac1a67b40bd35818ae6104d0726989a05a8007f7cf732b03b8170289a017891bb626df10660f2965979561bc7320f1fbe176367c0f1df512b7928d904e0208bd7dec9aab2651fddad6e21d5224459ec771a92132942f416e69618429590380b518023de9347a913b3ed50fc763394b2135573f5123478a31f300182bec74361dd9ccc0843d02852e41fdfefa71fa68329d93bf4908f41e43b9de42769fe2edcd673bf17c1f2f8095f52a02ec55dace4f10f78b2d20ddb48e006c1725bf21b447dcc1e399d122ec0593f31a80b4c4c321029f3eed50d86e5322d7750234b887b7cf06f9ab2e70fdeeba533be36cac9d75f480c8afa025028cb16a11e5fb5183ea752831e2a3b309cce66b1109ae20c5917e539438827e8d3401ec9a8aac795b1915c1433336491984aee906ad310d2a46f021279b58e0ab9ef402110000000002af2eac00000000000000000009b5e9a2170ec79f137af84344aa5146786c042198f6d773eb89d1390e3c867c6dfd09f55cb3794876bfe9741e22f84931987a61db87a053c56b54bd49742385e5b337801cd374521468f68c942c8af5e4ba070584a0699e4343855dbfcee154d2e71308d760c5b1e5c2250c3178ad27cf2b5f18fca9e53aac056d113a419648f41942e0989886abb01e93bb03db9af70b434ed62c489876e90b2d1108b4c6a8f03e535201c3650e2e1dfca05632efb66987cc735f643420205614c599a6f6385f79354039cab6546f5e12a846a83d747596dec9490b6da954c41639079540fdbd911829fcb753741b6c138f5ce8cd11a4d9dbc2eccb895192c63d3458165e63ba5acfd9ac97fecf7451d82d7b9b5278712ccdf978c7c682c4ebc606552726b882^M
 dropping connection
2018-Nov-26 04:16:58.510867 INFO    [protocol] [192.241.131.171:60935 INC] Sync data returned unknown top block: 153559 -> 154655 [1096 blocks (3 days) behind]
2018-Nov-26 04:16:58.510867 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-26 04:16:59.459174 INFO    [protocol] [88.214.241.183:40214 INC] Sync data returned unknown top block: 153559 -> 153729 [170 blocks (0 days) behind]
2018-Nov-26 04:16:59.459174 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-26 04:17:00.097733 INFO    [protocol] [191.255.112.198:65531 INC] Sync data returned unknown top block: 153559 -> 154655 [1096 blocks (3 days) behind]
2018-Nov-26 04:17:00.097733 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-26 04:17:00.138557 INFO    [protocol] [201.80.137.66:8313 OUT] Sync data returned unknown top block: 153559 -> 154655 [1096 blocks (3 days) behind]
2018-Nov-26 04:17:00.138557 INFO    [protocol] SYNCHRONIZATION started
2018-Nov-26 04:17:00.165089 ERROR   [protocol] [192.241.131.171:60935 INC] sent wrong block: failed to parse and validate block: ^M
0600f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f70100cce0dddf05f18fd86dfd2a2d2d5bc8b4ae33994921b8afed5fa75faa7142d78cb4e00241f78a3821d701010000002303210033bbf40739e1d15af824f68ac905084ca83cfbaa483eb8d4cd8584982be2459801e2af0901ffd8af090af9fbdff90302403f52f797317affa624308ebc668474db3ee243e629a2036396e9cead942678f9fbdff903021fa9dd8954415161d4cb1077f68423836afc9df1f646c84b41da44a1311b38d58c0702da8e3efa57633556ac1a67b40bd35818ae6104d0726989a05a8007f7cf732b03b8170289a017891bb626df10660f2965979561bc7320f1fbe176367c0f1df512b7928d904e0208bd7dec9aab2651fddad6e21d5224459ec771a92132942f416e69618429590380b518023de9347a913b3ed50fc763394b2135573f5123478a31f300182bec74361dd9ccc0843d02852e41fdfefa71fa68329d93bf4908f41e43b9de42769fe2edcd673bf17c1f2f8095f52a02ec55dace4f10f78b2d20ddb48e006c1725bf21b447dcc1e399d122ec0593f31a80b4c4c321029f3eed50d86e5322d7750234b887b7cf06f9ab2e70fdeeba533be36cac9d75f480c8afa025028cb16a11e5fb5183ea752831e2a3b309cce66b1109ae20c5917e539438827e8d3401ec9a8aac795b1915c1433336491984aee906ad310d2a46f021279b58e0ab9ef402110000000002af2eac00000000000000000009b5e9a2170ec79f137af84344aa5146786c042198f6d773eb89d1390e3c867c6dfd09f55cb3794876bfe9741e22f84931987a61db87a053c56b54bd49742385e5b337801cd374521468f68c942c8af5e4ba070584a0699e4343855dbfcee154d2e71308d760c5b1e5c2250c3178ad27cf2b5f18fca9e53aac056d113a419648f41942e0989886abb01e93bb03db9af70b434ed62c489876e90b2d1108b4c6a8f03e535201c3650e2e1dfca05632efb66987cc735f643420205614c599a6f6385f79354039cab6546f5e12a846a83d747596dec9490b6da954c41639079540fdbd911829fcb753741b6c138f5ce8cd11a4d9dbc2eccb895192c63d3458165e63ba5acfd9ac97fecf7451d82d7b9b5278712ccdf978c7c682c4ebc606552726b882^M
 dropping connection
`

**Comment by prox443** [comment]
I also tried to force nodes, but that doesn't solve my problem.

./niobiod --add-priority-node 191.255.112.198:8313 --add-priority-node 191.188.73.99:57871

**Comment by helder-garcia** [comment]
Please download version 1.6.7. It’s a mandatory update.

**Comment by prox443** [comment]
Thk :)
