### ISSUE TITLE
Error method "createAddress" Walletd JSON RPC API

### ISSUE THREAD

**Issue by adrianleite** [niobio-cash/niobio-node-daemon#39]
When using the "createAddress" method using a spend key, the wallet corresponding to the keys is not created. Always create a new wallet.
Reference: https://wiki.niobiocash.money/walletd-json-rpc-api-createAddress

Ao utilizar o método "createAddress" utilizando uma spend key não é criado a carteira correspondente as chaves. Sempre cria-se uma nova carteira.

**Comment by helder-garcia** [comment]
Please refer to the following guide on how to recover an address when using walletd.
https://wiki.niobiocash.money/walletd-json-rpc-api#how-to-protect-walletd-container-and-addresses
