### ISSUE TITLE
Failed to run MSBuild command

### ISSUE THREAD

**Issue by fykos** [niobio-cash/niobio-node-daemon#4]
Ao tentar compilar deu esse erro, o que pode ser? 
o visual studio que está instalado é o 2015

D:\Dados Importantes\Downloads\niobio-node-daemon-master\niobio-node-daemon-mast
er\build>cmake -G "Visual Studio 12 Win64" ..
CMake Error at CMakeLists.txt:17 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    O sistema não pode encontrar o arquivo especificado

-- Configuring incomplete, errors occurred!
See also "D:/Dados Importantes/Downloads/niobio-node-daemon-master/niobio-node-d
aemon-master/build/CMakeFiles/CMakeOutput.log".

**Comment by soldate** [comment]
tenta 
cmake -G "Visual Studio 15 2017 Win64" ..

**Comment by fykos** [comment]
Deu a mesma coisa...

`
D:\Dados Importantes\Downloads\niobio-node-daemon-master (1)\niobio-node-daemon-
master\build>cmake -G "Visual Studio 15 2017 Win64" ..
-- Selecting Windows SDK version  to target Windows 6.1.7601.
CMake Error at CMakeLists.txt:17 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    O sistema não pode encontrar o arquivo especificado



-- Configuring incomplete, errors occurred!
See also "D:/Dados Importantes/Downloads/niobio-node-daemon-master (1)/niobio-no
de-daemon-master/build/CMakeFiles/CMakeOutput.log".

`

No arquivo CMakeOutput.log deu isso:
`The system is: Windows - 6.1.7601 - AMD64`

**Comment by helder-garcia** [comment]
Desculpe, mas isso não é issue do projeto. É um problema de instalação ou configuração do Visual Studio.
