### ISSUE TITLE
Implementation of the "validateAddress" method!

### ISSUE THREAD

**Issue by adrianleite** [niobio-cash/niobio-node-daemon#40]
One suggestion would be the implementation of the "validateAddress".
"validateAddress" method allows you to check if provided address is valid.
Reference:
https://github.com/seredat/karbowanec/wiki/RPC-Wallet-API#Validate_address

Uma sugestão seria a implementação do "validateAddress".
O método "validateAddress" permite verificar se o endereço fornecido é válido.

**Comment by helder-garcia** [comment]
Implemented on version 1.6.8
